export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const INCREASE_COUNTER_ASYNC = 'INCREASE_COUNTER_ASYNC';
export const DECREASE_COUNTER_ASYNC = 'DECREASE_COUNTER_ASYNC';